### ISSUE TITLE
Responsiveness : Menu header becomes blank on smaller screens

### ISSUE THREAD

**Issue by lemetice** [silicon-mountain/smconf.org#16]
The menu header is blank on smaller screen. The green color reappears on scrolling.

**Comment by ch3ck** [comment]
Could you add a screenshot here? @lemetice

**Comment by lemetice** [comment]
Here are the screenshots 
![smconf](https://cloud.githubusercontent.com/assets/7753330/14603485/d0ece014-0565-11e6-955d-2364f4980d48.png)

When clicked on blank menu 
![smconfmenu](https://cloud.githubusercontent.com/assets/7753330/14603525/25f98210-0566-11e6-8261-0683e4264c61.png)

**Comment by ch3ck** [comment]
I see the issue, I don't know why that's happened. @prestb Any ideas here. Any ways @lemetice you could make a PR to fix this. I'll merge.

**Comment by prestb** [comment]
Issues where? Github or the site?

**Comment by ch3ck** [comment]
On the site, Look at the screenshots, it does not render properly on mobile. I don't know the issue there. Please check it out.

**Comment by prestb** [comment]
Which screenshot, everything is fine when I check

**Comment by ch3ck** [comment]
Have you seen the screenshots by @lemetice ? @prestb

**Comment by prestb** [comment]
ouch...yeah. i have the issue

**Comment by prestb** [comment]
@lemetice are you working on it?

**Comment by prestb** [comment]
@Ch3ck if u still have the old code, then it will be good to push it.
Cuz everything was working well there or the version that tah uploaded on GAE, i think we can use that

**Comment by ch3ck** [comment]
I don't have any old code. I don't think @lemetice is working on it. You could just fix it. It's just a mobile rendering issue

**Comment by prestb** [comment]
ok.

**Comment by prestb** [comment]
@Ch3ck i just did a small hackaround, check and let me know if its ok

**Comment by ch3ck** [comment]
Have you pushed the code yet?

**Comment by prestb** [comment]
@Ch3ck yes

**Comment by ch3ck** [comment]
@lemetice Issue fixed. Pull the recent changes.

**Comment by lemetice** [comment]
@prestb I didn't clone the project. I found the issue on production at [http://smconf2016.appspot.com/](url) so can't pull and test. Please update that version online.

**Comment by prestb** [comment]
```
    Subject Line (for proofing, doesn't show in actual email)
```

https://www.digitalocean.com                         == Deploy a Server
For Free! ==

  Your friend donyohel has been using DigitalOcean – a cloud hosting
service designed just for developers – and thought you might want to give
it a shot. You can deploy a server in 55 seconds from our control panel or
use our simple API. 

 Because you’ve been invited by a friend, we’d like to give you a $10
credit to try it out. Just use this link to create an account and you’ll
be credited automatically.

 Redeem Your Credit
https://cloud.digitalocean.com/accept?code=2ca10bc66fed88&amp;utm_campaign=Referral_Invite&amp;utm_medium=Referral_Program&amp;utm_source=Mandrill

  Happy Coding,
 DigitalOcean 

```
        © DigitalOcean <http://do.co/email_twitter>
```

http://do.co/email_gplus http://do.co/email_facebook

**Comment by prestb** [comment]
```
    Subject Line (for proofing, doesn't show in actual email)
```

https://www.digitalocean.com                         == Deploy a Server
For Free! ==

  Your friend donyohel has been using DigitalOcean – a cloud hosting
service designed just for developers – and thought you might want to give
it a shot. You can deploy a server in 55 seconds from our control panel or
use our simple API. 

 Because you’ve been invited by a friend, we’d like to give you a $10
credit to try it out. Just use this link to create an account and you’ll
be credited automatically.

 Redeem Your Credit
https://cloud.digitalocean.com/accept?code=6c5c5871d55a86&amp;utm_campaign=Referral_Invite&amp;utm_medium=Referral_Program&amp;utm_source=Mandrill

  Happy Coding,
 DigitalOcean 

```
        © DigitalOcean <http://do.co/email_twitter>
```

http://do.co/email_gplus http://do.co/email_facebook
